#!/bin/bash
set -x

action="$1"
cur_version="$2"


. /usr/share/debconf/confmodule 

. /usr/share/dbconfig-common/dpkg/config.mysql

if ! dbc_go openhie-pr-site $@ ; then
        echo 'Automatic configuration of openhie-pr-site using dbconfig-common failed!'
fi

exit 0
